twogood/unshield

lib/convert_utf/CMakeLists.txt

I'm guessing from the fact that `libunshield` has soversions set up but `libconvert_utf` does not that the latter is meant to be an internal library and should always be static.  If that is incorrect, please reject the PR, thanks :)
P.S. are the cmake variables supposed to be named `HEADES` instead of `HEADERS`? (Three places)

Always build libconvert_utf as a static library

---

CMakeLists.txt
lib/libunshield.c
lib/libunshield.h
lib/unshield_config.h.in
src/unshield.c

Some old InstallShield archives store filenames in locale-dependent codepages. This is usually not a huge problem since most installers mostly use ASCII characters, but many installers that use [international codepages](https://msdn.microsoft.com/en-us/goglobal/bb964654) may have their filenames completely clobbered. This patch adds an option `-e` which allows a character encoding to be converted to the user's locale codepage when writing files to the disk.
It might be better to somehow include this functionality in libunshield instead of the unshield binary, but that would have been a much bigger change and I wasn't sure it would fit the scope of the project.

Add option for character encoding

---

lib/file.c

For individual files larger than 2GB inside the .cab
'int bytes_left' will be treated as a negative number, so
change it to 'unsigned int' to work properly.

Fix for larger than 2GB file inside .cab

---

src/unshield.c

This fixes the compilation for those who don’t have `iconv`.

Don't use iconv_t unless HAVE_ICONV is set

---

src/unshield.c

path is not defined, but we have prefix.
this fixes a build failure on systems which do not have PATH_MAX:
/<<PKGBUILDDIR>>/src/unshield.c: In function 'extract_file':
/<<PKGBUILDDIR>>/src/unshield.c:373:25: error: 'path' undeclared (first use in this function)
path_max = pathconf(path, _PC_PATH_MAX);

fix pathconf call on prefix instead of path

---

lib/CMakeLists.txt

while 0.0.0 is probably not exactly right, this is what was
shipped in unshield up to 1.2. the change to cmake in 1.3
made the version change to ${PROJECT_VERSION}, which seems wrong,
as library versions usually don't relate to the project version.
there were no symbol changes between 1.0 and 1.3.
1.4 only introduced a new symbol (unshield_is_unicode) which does
not warrant to bump the soname.
fixes #41

revert SOVERSION back to 0 and library version to 0.0.0

---

CMakeLists.txt

* Debian requires shared libs to be PIC everywhere, not only on x86_64
* unshied fails to build on hppa and kfreebsd-amd64 without PIC

always generate position independent code

---

test/v0/avigomanager.sh
test/v0/the-feeble-files-spanish.sh
test/v5/CVE-2015-1386/CVE-2015-1386.sh

that way you can run the tests against the properly installed binary using
UNSHIELD=/usr/bin/unshield ./run-tests.sh

allow overriding the unshield binary used in tests

---

lib/helper.c
lib/libunshield.c
src/unshield.c

_BSD_SOURCE is deprecated, see features.h of GNU libc 2.24:
_BSD_SOURCE and _SVID_SOURCE are deprecated aliases for
_DEFAULT_SOURCE.  If _DEFAULT_SOURCE is present we do not
issue a warning; the expectation is that the source is being
transitioned to use the new macro.
Set both for now, so we can remove _BSD_SOURCE later.
This also fixes failures with -Werror on recent systems.

set _DEFAULT_SOURCE together with _BSD_SOURCE

---

lib/helper.c

the code was copied from src/unshield.c, but the include was missing and "prefix" was undefined in that context

fix pathconf call introduced in 7f302201

---

src/CMakeLists.txt

Hi.
I had a problem linking output binaries on Windows using GCC 7.1 (installed from Scoop), CMake 3.9 (from Scoop) and zlib 1.2.3 (from GnuWin32 package). I had to explicitly link `iconv` in order to build it.
Kind regards,
Vladimir.

Enabled Windows build with CMake and GCC.

---

.travis.yml

container builds: https://docs.travis-ci.com/user/migrating-from-legacy/ (faster, more resources)
trusty builds: https://docs.travis-ci.com/user/trusty-ci-environment/ (updated toolchain)
scan-build: http://clang-analyzer.llvm.org/ (runs with both gcc and clang, allowed to fail)
If wanted, you can use github pages to upload travis' generated detailed reports. Example:
http://librecad.github.io/static-analyzer-reports/
(deployed from travis with: https://github.com/LibreCAD/LibreCAD/blob/master/CI/static-analyzer-reports.sh)
should be ready for merge

travis updates: trusty, container builds, optional scan-build

---

src/unshield.c
win32_msvc/unistd.h

`lib/helper.c` includes `unistd.h`, which causes duplicate symbols for
opterr, optind, possibly more, when linking with MSVC.

Move getopt.h include to fix linking with MSVC

---

lib/helper.c

Presently, `unshield_utf16_to_utf8` creates a buffer that has 2 bytes for every UTF-16 codepoint.
Unfortunately, this isn't large enough to hold characters in the range `U+0800` to `U+FFFF`, so the function would just `abort()` with no error message.
This sets the buffer to 3 bytes for every UTF-16 codepoint.
With this change, I'm now able to list the contents of InstallShield v23 CAB files that contain Japanese component and file names (eg: `ｱﾌﾟﾘｹｰｼｮﾝ実行可能ﾌｧｲﾙ`).

fix: unshield_utf16_to_utf8 buffer too small for U+0800-U+FFFF chars

---

CMakeLists.txt
src/unshield.c

Not sure about side effects by introducing the _patch_ version number part.
Might this break packaging for some Linux distribution?

Fix version and copyright notice (fixes #82)

---

CMakeLists.txt

> Compatibility with versions of CMake older than 2.8.12 is now deprecated and will be removed from a future version. Calls to cmake_minimum_required() or cmake_policy() that set the policy version to an older value now issue a deprecation diagnostic.
https://cmake.org/cmake/help/latest/release/3.19.html#deprecated-and-removed-features

Fix: CMake older than 2.8.12 is now deprecated

---

src/unshield.c

As discussed in #150 the command line options are not used, therefor we could remove them for now.
The code is not lost if any of the features will be implemented.

Remove unused command line options.

---

.github/workflows/cmake.yml

Fixes the following warning:
```
CMake Warning:
Manually-specified variables were not used by the project:
CMAKE_BUILD_STATIC
```
The variables actual name is **BUILD_STATIC**, but it is not needed for the moment.

Remove unused CMake variable in workflow.

---

.github/workflows/codeql-analysis.yml

For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

Upgrade to CodeQL Action v2 (v1 will be deprecated on December 7th, 2022)

---

lib/libunshield.c

Found via static analysis - file gets leaked in a couple of edge cases.

Fix leaking handle in edge cases.

---

.github/workflows/cmake.yml
.github/workflows/codeql-analysis.yml

Node.js 12 actions are deprecated.
Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

GitHub Actions: Update to actions/checkout@v3

---

.github/workflows/cmake.yml

With this PR Windows binaries based on MinGW are built and tested afterwards.
This PR should make the following PRs/issues obsolete and might be closed:
- https://github.com/twogood/unshield/pull/57
- https://github.com/twogood/unshield/pull/91
- https://github.com/twogood/unshield/issues/33

Refactor workflow for proper MinGW support.

---

lib/file.c

While investigating #156 I found an unrelated potential problem.

Fix possible copy and paste mistake in 'unshield_file_save_old'.

---

lib/CMakeLists.txt
lib/libunshield.h

Follow-up to #178
* Update API naming for clarity and consistency by renaming `UNSHIELD_DLLEXPORT` to `UNSHIELD_API`. This change enhances naming clarity, making the purpose of the macro more intuitive and aligned with common naming conventions in cross- platform libraries.
* Optimize performance with export/import directives. By differentiating between `__declspec(dllexport)` and `__declspec(dllimport)` in Windows builds, this adjustment improves the performance of dynamic linking, ensuring efficient symbol resolution and potentially reducing binary size.
* Enhance flexibility in CMake configuration. Applying `PRIVATE` and `PUBLIC` specifiers in `target_compile_definitions` ensures that `UNSHIELD_EXPORT` is used internally within the library, while `UNSHIELD_DYNAMIC_LIBRARY` is …

Improve dll export/import definition

---

.github/workflows/codeql-analysis.yml

For more information see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

Update to CodeQL Action v3.
